lib/crawlapp_web/router.ex
defmodule CrawlappWeb.Router do
  use CrawlappWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {CrawlappWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CrawlappWeb do
    pipe_through :browser
    get "/", PageController, :index
    post "/", CrawlController, :post
    get "/upfile", CrawlController, :index
    post "/upfile", CrawlController, :postfile
    get "/download", CrawlController, :download
    get "/page/:page", CrawlController, :get_films_by_page
  end

  scope "/category/:category", CrawlappWeb do
    pipe_through :browser
    get "/", CrawlController, :get_films_by_category
    get "/page/:page", CrawlController, :get_films_by_category_with_page
  end

  scope "/director/:director", CrawlappWeb do
    pipe_through :browser
    get "/", CrawlController, :get_films_by_director
    get "/page/:page", CrawlController, :get_films_by_director_with_page
  end

  scope "/national/:national", CrawlappWeb do
    pipe_through :browser
    get "/", CrawlController, :get_films_by_national
    get "/page/:page", CrawlController, :get_films_by_national_with_page
  end

  # Other scopes may use custom stacks.
  # scope "/api", CrawlappWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: CrawlappWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/crawlapp_web/controllers/crawl_controller.ex
defmodule CrawlappWeb.CrawlController do
  use CrawlappWeb, :controller
  alias Core
  alias Crawlapp.Repo
  alias Crawlapp.Film
  alias Crawlapp.Category
  import Ecto.Query


  @spec index(Plug.Conn.t(), any) :: Plug.Conn.t()
  def index(conn, _params) do
    render conn, "index.html", non: conn
  end

  def post(conn, %{"url" => url}) do
    # data: [%{films: films, category: catetgory}, %{films: films, category: catetgory}, ...]
    data = Core.crawl_categories([url])
    post_data_to_database(data)

    get_films_by_page(conn, %{"page" => "1"})
  end

  def postfile(conn, %{"inputfile" => inputfile}) do
    {:ok, content} = File.read(inputfile.path)
    urls = String.split(content, "\r\n")
    # overlap with post function
    data = Core.crawl_categories(urls)
    post_data_to_database(data)

    get_films_by_page(conn, %{"page" => "1"})
  end

  defp render_films(conn, params) do
    categories = Repo.all(from f in Category, select: f.category)
    directors = Repo.all(from f in Film, distinct: true, select: f.director)
    nationals = Repo.all(from f in Film, distinct: true, select: f.national)

    chunk = 20
    num_of_page =  ceil(params.num_of_film/chunk)
    offset = chunk*(params.page-1)

    # get prefix of href and list of films for each page
    {pre_href, films} =
      cond do
        params.filter_by.by_category ->
          pre_href = "/category/" <> params.filter_by.category
          films = Repo.all(from f in Film, select: f, limit: ^chunk, offset: ^offset, where: f.category == ^params.filter_by.category_id)
          {pre_href, films}
        params.filter_by.by_director ->
          pre_href = "/director/" <> params.filter_by.director
          films = Repo.all(from f in Film, select: f, limit: ^chunk, offset: ^offset, where: f.director == ^params.filter_by.director)
          {pre_href, films}
        params.filter_by.by_national ->
          pre_href = "/national/" <> params.filter_by.national
          films = Repo.all(from f in Film, select: f, limit: ^chunk, offset: ^offset, where: f.national == ^params.filter_by.national)
          {pre_href, films}
        true ->
          pre_href = ""
          films = Repo.all(from f in Film, select: f, limit: ^chunk, offset: ^offset)
          {pre_href, films}
      end

    full_params = Map.merge(params, %{films: films, num_of_page: num_of_page, directors: directors, nationals: nationals, categories: categories, pre_href: pre_href})
    render conn, "download.html", params: full_params
  end


  def get_films_by_page(conn, %{"page" => page}) do
    num_of_film = from(f in Film, select: f.id) |> Repo.aggregate(:count, :id)
    filter_by = %{by_category: false, by_director: false, by_national: false}
    render_films(conn, %{page: String.to_integer(page), num_of_film: num_of_film, filter_by: filter_by})
  end

  def get_films_by_director(conn, %{"director" => director}) do
    get_films_by_director_with_page(conn, %{"director" => director, "page" => "1"})
  end

  def get_films_by_director_with_page(conn, %{"director" => director, "page" => page}) do
    if director == "all" do
      redirect(conn, to: "/page/1")
    else
      num_of_film = from(f in Film, select: f.id, where: f.director == ^director) |> Repo.aggregate(:count, :id)
      filter_by = %{by_category: false, by_director: true, by_national: false, director: director}
      render_films(conn, %{page: String.to_integer(page), num_of_film: num_of_film, filter_by: filter_by})
    end
  end

  def get_films_by_national(conn, %{"national" => national}) do
    get_films_by_national_with_page(conn, %{"national" => national, "page" => "1"})
  end

  def get_films_by_national_with_page(conn, %{"national" => national, "page" => page}) do
    if national == "all" do
      redirect(conn, to: "/page/1")
    else
      num_of_film = from(f in Film, select: f.id, where: f.national == ^national) |> Repo.aggregate(:count, :id)
      filter_by = %{by_category: false, by_director: false, by_national: true, national: national}
      render_films(conn, %{page: String.to_integer(page), num_of_film: num_of_film, filter_by: filter_by})
    end
  end

  def get_films_by_category_with_page(conn, %{"category" => category, "page" => page}) do
    if category == "all" do
      redirect(conn, to: "/page/1")
    else
      [category_id] = Repo.all(from c in Category, select: c.id, where: c.category == ^category)
      num_of_film = from(f in Film, select: f.id, where: f.category == ^category_id) |> Repo.aggregate(:count, :id)
      filter_by = %{by_category: true, by_director: false, by_national: false, category_id: category_id, category: category}
      render_films(conn, %{page: String.to_integer(page), num_of_film: num_of_film, filter_by: filter_by})
    end
  end

  def get_films_by_category(conn, %{"category" => category}) do
    get_films_by_category_with_page(conn, %{"category" => category, "page" => "1"})
  end

  defp post_data_to_database(data) do
    # data: [%{films: films (list), category: catetgory}, %{films: films, category: catetgory}, ...]
    Enum.each(data, fn cate ->
      Repo.insert!(
        %Category{category: cate.category},
        on_conflict: :nothing
      )
      [category_id] = Repo.all(from f in Category, select: f.id, where: f.category == ^cate.category)
      Enum.each(cate.films, fn film ->
        Repo.insert(
          %Film{category: category_id, title: film.title, link: film.link, full_series: film.full_series, episode_number: film.number_of_episode, thumnail: film.thumbnail, year: film.year, director: film.director, national: film.national},
          on_conflict: :nothing
        )
      end)
    end)
  end





  def download(conn, _params) do
    path = Application.app_dir(:crawlapp, "priv/static/assets/result1.json")
    send_download(conn, {:file, path})
  end

end

lib/crawlapp_web/views/crawl_view.ex
defmodule CrawlappWeb.CrawlView do
  use CrawlappWeb, :view
end

lib/crawlapp_web/templates/crawl/download.html.heex
<div class="row">
    <div class="col-9"></div>
    <div class="col-1 dropdown">
        <a class="btn btn-secondary dropdown-toggle float-right" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
            Category
        </a>

        <ul class="dropdown-menu scrollable-menu" aria-labelledby="dropdownMenuLink">
            <li><a class="dropdown-item" href={"/category/all"}>All</a></li>
            <%= for category <- @params.categories do %>
                <li><a class="dropdown-item" href={"/category/" <> category}><%= category %></a></li>
            <% end %>
            
        </ul>
    </div>

    <div class="col-1 dropdown">
        <a class="btn btn-secondary dropdown-toggle float-right" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
            Directory
        </a>

        <ul class="dropdown-menu scrollable-menu" aria-labelledby="dropdownMenuLink">
            <li><a class="dropdown-item" href={"/director/all"}>All</a></li>
            <%= for director <- @params.directors do %>
                <li><a class="dropdown-item" href={"/director/" <> director}><%= director %></a></li>
            <% end %>
            
        </ul>
    </div>

    <div class="col-1 dropdown">
        <a class="btn btn-secondary dropdown-toggle float-right" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
            National
        </a>

        <ul class="dropdown-menu scrollable-menu" aria-labelledby="dropdownMenuLink">
            <li><a class="dropdown-item" href={"/national/all"}>All</a></li>
            <%= for national <- @params.nationals do %>
                <li><a class="dropdown-item" href={"/national/" <> national}><%= national %></a></li>
            <% end %>
            
        </ul>
    </div>
</div>



<ul class="index-nav my-3">
    <li>
        <a href={@params.pre_href <> "/page/" <> Integer.to_string(if @params.page-1 >= 1, do: @params.page-1, else: @params.num_of_page)}>
            <div class="btn btn-info">Prev</div>
        </a>
    </li>
    <%= 
    half = 2
    start_index = if @params.page-half <= 1, do: 1, else: @params.page-half
    end_index = if @params.page+half >= @params.num_of_page, do: @params.num_of_page, else: @params.page+half

    [start_loop, end_loop] =
    if @params.num_of_page <= 5 do
        [1, @params.num_of_page]
    else
        start_loop = if end_index - @params.page < 2, do: end_index - 4, else: start_index
        end_loop = if @params.page - start_index < 2, do: start_index + 4, else: end_index
        [start_loop, end_loop]
    end
        
    for i <- (start_loop)..(end_loop) do %>
        <li>
            <a href={@params.pre_href <> "/page/" <> Integer.to_string(i)}>
                <div class={"btn btn-info" <> if i==@params.page, do: " active", else: ""}><%= i %></div>
            </a>
        </li>
    <% end %>
    <li>
        <a href={@params.pre_href <> "/page/" <> Integer.to_string(if @params.page+1 <=  @params.num_of_page, do: @params.page+1, else: 1)}>
            <div class="btn btn-info">Next</div>
        </a>
    </li>
    <li>
        <a href={@params.pre_href <> "/page/" <> Integer.to_string(@params.num_of_page)}>
            <div class="btn btn-info">Last</div>
        </a>
    </li>
</ul>


<div class="flex-container">
    <%= for film <- @params.films do %>
        <div class="item">
            <div class="item-top">
                <div class="info">
                    <%= film.director %>
                    <br>
                    <%= film.national %>
                    <br>
                    Episode: <%= film.episode_number %>
                </div>
                <a href={film.link}>
                    <img src={String.slice(film.thumnail, 22..-3)} class="thumbnail" width="200px" height="300px">
                </a>
            </div>
            
            <div class="title my-3"><%= film.title %></div>
        </div>
    <% end %>
</div>


<div class="btn btn-info float-right my-3 font-weight-bold">
    <%= link raw('<span>Download</span>'), to: Routes.crawl_path(@conn, :download), class: "nav-link" %>
</div>  

lib/crawlapp_web/templates/crawl/index.html.heex
<%= form_for @non, Routes.crawl_path(@conn, :postfile), [multipart: true],  fn f -> %>
  <div class="form-group">
    <label>Input file</label>
    <%= file_input f, :inputfile, class: "form-control" %>
  </div>
  <%= submit "Submit", class: "btn btn-primary" %>
<% end %>